### ISSUE TITLE
[Feature] Legal Database Footer isn't consistent with the current Vocabulary design system

### ISSUE THREAD

**Issue by babyteega** [creativecommons/legaldb#196]
## Problem
The footer does not follow the _current_ Vocabulary design system, it contains the Instagram link instead of the Mastodon link as the current vocabulary does. Also some other discrepancies, like the difference in the 'Donate' button 

## Description
The current Footer Vocabulary
<img width="914" alt="footer correct" src="https://github.com/user-attachments/assets/180d3238-9d54-4f74-86b8-9640cae478b5">

The Footer for the Legal Database Page
<img width="922" alt="wrong footer" src="https://github.com/user-attachments/assets/ed49cffb-b697-42c9-b157-c01cea9abe0b">

 

## Additional context
- The link to the Mastodon should be included instead of the Instagram link, to improve general UX
- [creativecommons/vocabulary](https://github.com/creativecommons/vocabulary/): _A cohesive system of design for Creative Commons_

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by egbadon-victor** [comment]
@TimidRobot this issue has been resolved!
