### ISSUE TITLE
[Feature] Mobile Menu on LegalDB website doesn't match the current Vocabulary design system

### ISSUE THREAD

**Issue by Netacci** [creativecommons/legaldb#197]
## Problem

The mobile menu on the LegalDB website does not align with the _current_ Vocabulary design system. The website uses a hamburger icon, and the UI of the opened menu is different from what is implemented in the design system, which uses a "Menu" button and a more aesthetically pleasing design.

LegalDb menu

![legal-menu](https://github.com/user-attachments/assets/cfdfe7a1-32d2-4719-ba73-0d2a733254f2)

LegalDb Open menu

![legal-menu-open](https://github.com/user-attachments/assets/46ac26b0-13d4-4ef1-8195-aac68a443b95)

Vocabulary menu

![vocab-menu](https://github.com/user-attachments/assets/b9266f62-1b4c-488e-a861-1f0f87fa0557)

Vocabulary open menu

![vocab-menu-open](https://github.com/user-attachments/assets/b7cf0dd7-ee5f-4a47-9074-b203c4e4e7fb)

## Description

To maintain consistency across projects, the mobile menu on the LegalDB website should be updated to match the UI guidelines from the design system.
This change will improve user experience and align the website with the design system's guidelines, making it more cohesive with the overall product design language.

## Alternatives

One alternative is keeping the current hamburger icon and menu button implementation, but this results in inconsistent design across projects.

## Additional context

The design system's mobile menu UI includes:
- "Menu" button in place of a hamburger icon.
- A more refined, aesthetically pleasing design when the menu is opened.
- Consistent use of typography, spacing, and colors as defined in the design system.
- [creativecommons/vocabulary](https://github.com/creativecommons/vocabulary/): _A cohesive system of design for Creative Commons_

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by Dev-JoyA** [comment]
@TimidRobot pls assign this issue to me .

Thanks
