### ISSUE TITLE
[Bug] Spanish translation for specific template text not displaying

### ISSUE THREAD

**Issue by rypptc** [creativecommons/legaldb#266]
## Description
The Spanish translation for specific text on the index.html template (located in legal_db/templates/legal_db/index.html) does not display on the site, despite the .po file containing the correct translation. Other translations on the site are working correctly.

## Reproduction
This is evident when navigating to the Spanish version of the home page. The text not translated is the following:

> This database includes [case law](https://legaldb.creativecommons.org/es/cases/) and [legal scholarship](https://legaldb.creativecommons.org/es/scholarship/) that relates to Creative Commons legal tools.
> Please note that the database is not comprehensive, and CC does not necessarily endorse the views of the courts or scholars whose decisions and writings are referenced. The content provided is purely informational, designed for those seeking to better understand the legal ecosystem in which the CC legal tools operate.

## Expectation
The specific text in index.html should display in Spanish, as defined in the .po file, when the language is set to Spanish via the dropdown.

## Screenshots
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/1a7234f6-1c35-4423-864b-867bbe823125">

## Environment
 - Device: Not environment-specific
 - OS: Not environment-specific
 - Browser: Google Chrome
 - Version: Not environment-specific
 - Other info: This is visible on the live website.

## Additional context
The .po file for Spanish includes the correct translation, and other text on the site is displaying in Spanish as expected. The issue appears isolated to this specific block of text on index.html.

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by rahulptl165** [comment]
Hi, @rypptc I have created pull request for this issue. please review when you are free.

**Comment by rypptc** [comment]
Hi, @rahulptl165 I'm not a maintainer, so I cannot approve or merge a PR. However, I think that the problem may not be related with the blocktrans structure, since it worked fine in my local machine as it was before. There may be another problem related to the compilation process or a caching issue. Let's wait for the review by the maintainers of the project.
