### ISSUE TITLE
Replace Vocabulary CDN

### ISSUE THREAD

**Issue by krysal** [creativecommons/legaldb#73]
## Problem

Currently the project is using Vocabulary via [CDN](https://github.com/creativecommons/caselaw/blob/9fdb32a1a40777aed7ecd2c54f3e19a858a378ad/legal_db/templates/legal_db/base.html#L12), this makes it quick to start using the components but has the downside that SCSS files cannot be imported, therefore variables and mixins already defined in the library cannot be used and they have to be duplicated here.

## Description

The goal is to be able to use the SCSS files of Vocabulary and make it easy to upgrade to future versions, replacing the CDN with a build process for these assets.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by darkshredder** [comment]
I would like to work on this

**Comment by krysal** [comment]
Hi @darkshredder, we want to avoid that two things: manually copying vocabulary files into the project and refactor the whole app (this was done recently from a Jekyll app). We want to keep dependencies low to reduce mainteinance burden, there is no a real need to use a frontend library like Vue or React for the moments.

The ideal solution I think, would be to create a pipeline process with webpack (or similar tool) to manage js dependencies with `npm`, something similar to what is done in the [CC Open Source site](https://github.com/creativecommons/creativecommons.github.io-source/).

Either way, you can send PR with your solution if you think it fits this requirements want and/or improves the development process to write styles with Vocabulary. Contributions are welcome, and thanks for your interest!
